url: https://brainhack-donostia.github.io
baseurl: 

# Site settings
title: BrainHack Donostia 2026
email: info.bhg-donostia@bcbl.eu
description: "Site for Brainhack Donostia 2026"


# Team names, titles and social links
people:
- name: Cristina Rius
  pic: cristinarius
  position: Co-chair
- name: François Steffann
  pic: francoissteffann
  position: Co-chair
- name: Vilani Rajapkse
  pic: vilani
  position: Treasury & Event Planning
- name: Anaam Qureshi
  pic: anaamqureshi
  position: Treasury & Event Planning
- name: Yixuan Zhu
  pic: yixuanzhu
  position: Treasury & Event Planning
- name: Emine Ayyıldız
  pic: emineayyildiz
  position: Event Planning
- name: Iria Nieto
  pic: irianieto
  position: PR & Design
- name: Nursena Arslan
  pic: nursenaarslan
  position: PR & Design
- name: Iñigo García
  pic: inigogarcia
  position: IT

social:
  - title: github
    url: http://github.com/Brainhack-Donostia
  - title: bluesky
    url: https://bsky.app/profile/bhdonostia.bsky.social
  - title: linkedin
    url: https://es.linkedin.com/in/brainhack-donostia-8b0a12227
  - title: instagram
    url: https://www.instagram.com/bhdonostia/

# Postal address (add as many lines as necessary)
address:
  - line: Mikeletegi Pasealekua, 69, 20009
  - line: Donostia-San Sebastiá
  - line: Gipuzkoa, Spain

# Build settings
markdown: kramdown
permalink: pretty
future: true

exclude:
  - CLAUDE.md
  - apps-script
  - docs
  - tools
