url: https://brainhack-donostia.github.io
baseurl: 

# Site settings
title: Brain Hack Donostia 2023
email: bhg-donostia@bcbl.eu
description: "Coming soon!"


# Team names, titles and social links
people:
- name: Ihintza Malharin
  pic: ihintzaM 
  position: Brainhack Donosti organizing chair
  social:
      url: https://www.bcbl.eu/en/ihintza-malharin

- name: Marco Flores-Coronado 
  pic: marcoFC
  position: Brainhack Donosti organizing chair
  social:
      url: https://www.bcbl.eu/en/marco-a-flores-coronado
- name: Chiara Luna Rivolta 
  pic: chiaraLR
  position: Brainhack Donosti treasury 
  social:
      url: https://www.bcbl.eu/en/chiara-luna-rivolta  
- name: Anique Schüller
  pic: aniqueS
  position: Brainhack Donosti treasury 
  social:
      url: https://www.bcbl.eu/en/anique-schuller
- name: Jiaqi (Mo) Mao
  pic: jiaqiM
  position: Brainhack Donosti treasury 
  social:
      url: https://www.bcbl.eu/en/jiaqi-mo-mao   
- name: Inés Chavarría 
  pic: inesC
  position: Brainhack Donosti projects
  social:
      url: https://www.bcbl.eu/en/ines-chavarria
- name:  Cristina Comella
  pic: cristinaC
  position: Brainhack Donosti projects 
  social:
      url: https://www.bcbl.eu/en/node/7402
- name: Yi-Ting (Silvia) Yang 
  pic: yi-tingY
  position: Brainhack Donosti projects 
  social:
      url: https://www.bcbl.eu/en/yi-ting-silvia-yang
- name:  Ana Bautista
  pic: anaB 
  position: Brainhack Donosti design
  social:
      url: https://www.bcbl.eu/en/leandro-lecca
- name: Leandro Lecca
  pic: leandroL
  position: Brainhack Donosti IT 
  social:
      url: https://www.bcbl.eu/en/leandro-lecca
- name: Ryland Miller 
  pic: rylandM
  position: Brainhack Donosti IT 
  social:
      url: https://www.bcbl.eu/en/node/7471
- name: Cesar Caballero-Gaudes 
  pic: CesarCG
  position: Brainhack Donosti talks
  social:
      url:  https://www.bcbl.eu/en/conocenos/equipo/cesar-caballero-gaudes  
- name: Garikoitz Lerma-Usabiaga
  pic: garikoitzLU
  position: Brainhack Donosti talks
  social:
      url: https://www.bcbl.eu/en/conocenos/equipo/garikoitz-lerma-usabiaga

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BHDonostia
  - title: github
    url: http://github.com/Brainhack-Donostia

# Postal address (add as many lines as necessary)
address:
  - line: Mikeletegi Pasealekua, 69, 20009
  - line: Donostia-San Sebastián
  - line: Gipuzkoa, Spain

# Build settings
markdown: kramdown
permalink: pretty
