url: https://brainhack-donostia.github.io
baseurl: 

# Site settings
title: BrainHack Donostia 2025
email: info.bhg-donostia@bcbl.eu
description: "Site for Brainhack Donostia 2025"


# Team names, titles and social links
people:
- name: Clementine Levy-Fidel
  pic: clementineL
  position: Chair 
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/clementine-levy-fidel
- name: Monika Utrosa Skerjanec
  pic: monikaU
  position: Chair
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/monika-utrosa-skerjanec
- name: Noemi Bonfiglio
  pic: noemiB
  position: Treasury
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/noemi-bonfiglio
- name: Joaquin  Ordonez
  pic: joaquinO
  position: Treasury
  social:
     - title: firefox
       url: https://www.bcbl.eu/en/joaquin-ordonez
- name: Jose Antonio Gonzalo Gimeno
  pic: joseA
  position: Treasury
  social:
     - title: firefox
       url: https://www.bcbl.eu/en/jose-antonio-gonzalo
- name: Melissa Donati 
  pic: melissaD
  position: Website/Design
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/melissa-donati
- name: Marco Flores-Coronado
  pic: marcoF
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/marco-a-flores-coronado
- name: Daniel Nieto Carrero
  pic: danielN
  position: IT
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/node/7816
- name: Francisca Campos Matias
  pic: franciscaC
  position: Program
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/francisca-campos-matias
- name: Irtisha Chakraborty 
  pic: irtishaC
  position: Program
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/irtisha-chakraborty
- name: Cristina Comella Luengo
  pic: cristinaC
  position: Program/Design
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/cristina-comella
- name: Chiara Bernini
  pic: chiaraB
  position: Design/Public relations
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/chiara-bernini
- name: Nirmitee Mulay
  pic: nirmiteeM
  position: Design/Public relations
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/nirmitee-mulay
- name: Antje Walter
  pic: antjeW
  position: Public relations
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/antje-walter
        # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

- name: Seyma Takir 
  pic: seymaT
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/seyma-takir

social:
  - title: github
    url: http://github.com/Brainhack-Donostia
  - title: bluesky
    url: https://bsky.app/profile/bhdonostia.bsky.social
  - title: linkedin
    url: https://es.linkedin.com/in/brainhack-donostia-8b0a12227
  - title: instagram
    url: https://www.instagram.com/bhdonostia/

# Postal address (add as many lines as necessary)
address:
  - line: Mikeletegi Pasealekua, 69, 20009
  - line: Donostia-San Sebastiá
  - line: Gipuzkoa, Spain

# Build settings
markdown: kramdown
permalink: pretty
