url: https://brainhack-donostia.github.io
baseurl: 

# Site settings
title: BrainHack Donostia 2025
email: info.bhg-donostia@bcbl.eu
description: "Site for Brainhack Donostia 2024"


# Team names, titles and social links
people:
- name: Clementine Levy-Fidel
  pic: clementineL
  position: Chair 
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/clementine-levy-fidel
- name: Monika Utrosa Skerjanec
  pic: monikaU
  position: Chair
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/monika-utrosa-skerjanec
- name: Noemi Bonfiglio
  pic: noemiB
  position: Treasury
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/noemi-bonfiglio
- name: Joaquin  Ordonez
  pic: joaquinO
  position: Treasury
  social:
     - title: firefox
       url: https://www.bcbl.eu/en/joaquin-ordonez
- name: Jose Antonio Gonzalo
  pic: joseA
  position: Treasury
  social:
     - title: firefox
       url: https://www.bcbl.eu/en/jose-antonio-gonzalo
- name: Manuela Ruzzoli
  pic: manuelaR
  position: Talks
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/manuela-ruzzoli
- name: Cesar Caballero-Gaudes
  pic: cesarC
  position: Talks 
  social:
    - title: firefox
      url: https://www.bcbl.eu/es/conocenos/equipo/cesar-caballero-gaudes 
- name: Alejandro Tabas
  pic: alejandroT
  position: Projects
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/alejandro-tabas
- name: Melissa Donati 
  pic: melissaD
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/melissa-donati
- name: Marco Flores-Coronado
  pic: marcoF
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/marco-a-flores-coronado
- name: Francisca Campos Matias
  pic: franciscaC
  position: Program
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/francisca-campos-matias
- name: Catarina Domingos
  pic: catarinaD
  position: Keep People Happy
  social:
    - title: firefox
      url: https://welcome.isr.tecnico.ulisboa.pt/author/catarinadomingos/
- name: Irtisha Chakraborty 
  pic: irtishaC
  position: Keep People Happy
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/irtisha-chakraborty





        # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BHDonostia
  - title: github
    url: http://github.com/Brainhack-Donostia

# Postal address (add as many lines as necessary)
address:
  - line: Mikeletegi Pasealekua, 69, 20009
  - line: Donostia-San Sebastiá
  - line: Gipuzkoa, Spain

# Build settings
markdown: kramdown
permalink: pretty
