url: https://brainhack-donostia.github.io
baseurl: 

# Site settings
title: BrainHack Donostia 2024
email: info.bhg-donostia@bcbl.eu
description: "Site for Brainhack Donostia 2024"


# Team names, titles and social links
people:
- name: Nirmitee Mulay
  pic: nirmiteeM
  position: Chair 
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/nirmitee-mulay
- name: Emanuele Ciardo
  pic: emanueleC
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/emanuele-ciardo
- name: Noemi Bonfiglio
  pic: noemiB
  position: Treasury
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/noemi-bonfiglio
- name: Joaquin  Ordonez
  pic: joaquinO
  position: Treasury
  social:
     - title: firefox
       url: https://www.bcbl.eu/en/joaquin-ordonez
- name: Maria de Almeida Ribeiro 
  pic: mariaAR
  position: Socials
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/maria-de-almeida-ribeiro
- name: Kirill Aksenov 
  pic: kirillA
  position: Socials
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/kirill-aksenov
- name: Manuela Ruzzoli
  pic: manuelaR
  position: Talks
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/manuela-ruzzoli
- name: Garikoitz Lerma-Usabiga
  pic: garikoitzL
  position: Talks 
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/garikoitz-lerma-usabiaga
- name: Alejandro Tabas
  pic: alejandroT
  position: Projects
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/conocenos/equipo/alejandro-tabas
- name: Ihintza Malharin
  pic: ihintzaM 
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/ihintza-malharin
- name: Melissa Donati 
  pic: melissaD
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/melissa-donati
- name: Marco Flores-Coronado
  pic: marcoF
  position: Website
  social:
    - title: firefox
      url: https://www.bcbl.eu/en/marco-a-flores-coronado

        # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BHDonostia
  - title: github
    url: http://github.com/Brainhack-Donostia

# Postal address (add as many lines as necessary)
address:
  - line: Mikeletegi Pasealekua, 69, 20009
  - line: Donostia-San Sebastiá
  - line: Gipuzkoa, Spain

# Build settings
markdown: kramdown
permalink: pretty
