name: "Submitted Projects"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 */12 * * *"  # Every 12 hours.

jobs:
  backup:
    runs-on: macos-latest
    name: Backup
    timeout-minutes: 15
    steps:
      -   uses: actions/checkout@v2
      -   name: Setup Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

      -   name: Setup Dependencies
          run: |
            pip install wget
            pip install pandas
      -   name: Populate projects page
          run: |
            python populate_projects.py

      -   name: Commit Changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Updated projects page with latest info on Google Sheets.
            commit_user_name: GitHub Actions
            commit_user_email: actions@github.com
            commit_author: GitHub Actions <actions@github.com>
